### PR TITLE
Upgrade to Terraform SDK provider 2.4.1

### PR DESCRIPTION
**Pull request by daniel-noland**
Simple bump to neweset Terraform SDK provider.
This was a major SDK version bump but only minor changes were required.
Specifically, the SDK provider [removed the `helper/hashcode` package](https://www.terraform.io/docs/extend/guides/v2-upgrade-guide.html#removal-of-helper-hashcode-package)
Based on my desire for MVP changes to accomplish this upgrade I went along with the advice detailed in the above link and simply used trivially modified versions of the public domain functions provided in that link.

As far as I can tell, this project does not strictly require the hash function to behave exactly this way.
However, the minimal change should make bisection easier if the version bump causes regressions.

### CODE REVIEW

**Comment by daniel-noland** [comment]
Just as a note, this is my first swing at Go as a language so please let me know if I messed up any conventions or you would like to see any modifications.

As I am not especially familiar with this project I don't know if these changes are desirable for your use case nor how to best do integration testing on this change set.
Thus I have left this as a draft PR for the moment.

**Comment by daniel-noland** [comment]
I do not understand exactly why the second patch in this series is necessary as I do not think I did anything to go-jira which should have provoked those type issues.
Thus, I left these as separate patches in the series.

That said, I am happy to squash these together if those changes make sense.

Upgrading this from draft as I think the change set can be meaningfully reviewed now.

**Comment by fourplusone** [comment]
Hi Daniel

Thanks a lot for your PR. The SDK update looks very good to me. However I'd like to take a closer look on the changed types for category & lead in order to make sure not to break anything. Can you tell my against which Version of JIRA you tested your changes?

**Comment by daniel-noland** [comment]
That makes sense, I was a little confused myself.
The (partially redacted) response from my Jira version query:

from

`rest/api/2/serverInfo`

I get

```json
{
  "version": "1001.0.0-SNAPSHOT",
  "versionNumbers": [
    1001,
    0,
    0
  ],
  "buildDate": "2021-01-24T13:25:17.000-0700",
  "scmInfo": "4dba4bbac82b4ed6e51419a8be618b7db816b071",
  "deploymentType": "Cloud",
  "buildNumber": 100154
}
```

Let me know if I can help with testing.  I don't have a non-production Jira environment to test against however.

**Comment by hh-nharward** [comment]
+1 on this PR - HashiCorp EOL'd v1 of their SDK effective July 31: https://discuss.hashicorp.com/t/end-of-life-timeline-for-v1-of-the-terraform-plugin-sdk/24991

**Comment by fourplusone** [comment]
Thanks for the heads up. I’ll have a look soon.

**Pull request merged**
